services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: client-dev
    ports:
      - "8081:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api-dev
    ports:
     - "4000:4000"
    volumes:
     - ./api:/api
     - /api/node_modules